id: IC0174AE2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T14:09:29+00:00'
last_modified: '2022-06-08T01:13:18.216024+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W15925
  title: གསོ་དཔྱད་ཀྱི་ལག་ལེན་དགོས་འདོད་ཀུན་འབྱུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    27D7:
      image_group_id: I1PD436
      title: ''
      total_pages: 272
      order: 1
      base_file: 27D7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
